# Generated by Django 4.2.11 on 2026-06-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('BAGS', 'School Bags'), ('STATIONERY', 'Stationery'), ('UNIFORMS', 'Uniforms'), ('SANITARY', 'Sanitary Products'), ('SPORTS', 'Sports Equipment'), ('CLASSROOM', 'Classroom Supplies'), ('MEDALS', 'Medals & Trophies'), ('OFFICE', 'Office Supplies'), ('ACCESSORIES', 'Other Accessories')], db_index=True, max_length=50, unique=True),
        ),
    ]
