from django.core.management.base import BaseCommand, CommandError
from django.contrib.auth import get_user_model
from django.db import transaction
from django.utils import timezone
import random

from apps.products.models import Product
from apps.orders.models import Order, OrderItem
from apps.transactions.models import Transaction


User = get_user_model()


class Command(BaseCommand):
    help = 'Create sample orders for a given user email. Useful for testing.'

    def add_arguments(self, parser):
        parser.add_argument('--email', required=True, help='Email of the user to create orders for')
        parser.add_argument('--count', type=int, default=1, help='Number of orders to create')
        parser.add_argument('--max-items', type=int, default=4, help='Maximum distinct items per order')

    def handle(self, *args, **options):
        email = options['email']
        count = options['count']
        max_items = options['max_items']

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            raise CommandError(f'No user found with email {email}')

        products = list(Product.objects.filter(is_active=True))
        if not products:
            raise CommandError('No active products found to create orders from')

        created = []
        for i in range(count):
            with transaction.atomic():
                order = Order.objects.create(
                    user=user,
                    school=getattr(user, 'school', None),
                    shipping_address=f"Auto-generated address {i+1}",
                    notes='Generated by create_sample_orders management command',
                    total_amount=0,
                    created_at=timezone.now(),
                )

                num_items = random.randint(1, min(max_items, len(products)))
                sampled = random.sample(products, num_items)
                for p in sampled:
                    qty = random.randint(1, 3)
                    OrderItem.objects.create(
                        order=order,
                        product=p,
                        quantity=qty,
                        unit_price=p.price,
                        discount_percentage=getattr(p, 'discount_percentage', 0) or 0,
                        tax_percentage=getattr(p, 'tax_percentage', 0) or 0,
                    )

                # Recalculate totals using model helper if present
                try:
                    order.calculate_total()
                except Exception:
                    # fallback: sum unit_price * qty
                    total = 0
                    for it in order.items.all():
                        total += it.unit_price * it.quantity
                    order.total_amount = total
                    order.save()

                # Create a mock transaction (COD) marking as completed
                Transaction.objects.create(
                    order=order,
                    user=user,
                    amount=order.total_amount,
                    status='COMPLETED',
                    payment_method='COD',
                    transaction_id=str(timezone.now().timestamp()).replace('.', '')[:24],
                    created_at=timezone.now(),
                )

                # Mark order confirmed if model supports
                try:
                    order.update_status('CONFIRMED')
                except Exception:
                    pass

                created.append(order.id)

        self.stdout.write(self.style.SUCCESS(f'Created {len(created)} orders for {email}: {created}'))
