# Generated by Django 4.2.11 on 2026-06-07 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('ORDER', 'Order'), ('PAYMENT', 'Payment'), ('SHIPPING', 'Shipping'), ('ACCOUNT', 'Account'), ('PROMOTION', 'Promotion'), ('SYSTEM', 'System')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('related_object_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx'), models.Index(fields=['category', 'created_at'], name='notificatio_categor_57c79b_idx')],
            },
        ),
    ]
